// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBFYOACDVP4-Mx4p5-QigBRkJJWrwOU6g4',
    appId: '1:745025917370:web:d61831a874be9632ef4d83',
    messagingSenderId: '745025917370',
    projectId: 'elective-project-131ae',
    authDomain: 'elective-project-131ae.firebaseapp.com',
    storageBucket: 'elective-project-131ae.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA_Z6EFIeM-lBcWlvozi-AD5SCVypDqQQ8',
    appId: '1:745025917370:android:1fa1f3037a2b505bef4d83',
    messagingSenderId: '745025917370',
    projectId: 'elective-project-131ae',
    storageBucket: 'elective-project-131ae.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC5rkWMS3OUvZr34Q45ENjYVKIZgN63qTA',
    appId: '1:745025917370:ios:75440c572aa2b23def4d83',
    messagingSenderId: '745025917370',
    projectId: 'elective-project-131ae',
    storageBucket: 'elective-project-131ae.appspot.com',
    iosClientId: '745025917370-i2o3r45grl59ms7pk67dhcl476bkfpu1.apps.googleusercontent.com',
    iosBundleId: 'com.example.electiveProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC5rkWMS3OUvZr34Q45ENjYVKIZgN63qTA',
    appId: '1:745025917370:ios:75440c572aa2b23def4d83',
    messagingSenderId: '745025917370',
    projectId: 'elective-project-131ae',
    storageBucket: 'elective-project-131ae.appspot.com',
    iosClientId: '745025917370-i2o3r45grl59ms7pk67dhcl476bkfpu1.apps.googleusercontent.com',
    iosBundleId: 'com.example.electiveProject',
  );
}
